name: Deploy Site (harvest -> GitHub Pages)

on:
  workflow_dispatch:   # lets you run it manually
  schedule:
    - cron: "5 12 * * *"  # runs daily at 12:05 UTC

permissions:
  contents: write  # allow committing events.json back to the repo

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (if you need extras)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run harvester
        env:
          ICS_FEEDS: ${{ vars.ICS_FEEDS }}   # put real .ics URLs in repo settings → Variables
        run: |
          python harvest.py || true
          mkdir -p docs/data
          if [ -f aom-events.json ]; then
            cp aom-events.json docs/data/events.json
          else
            echo '{"meta":{"ts_utc":"'$(date -u +%Y-%m-%dT%H:%M:%SZ)'","sources":["none"]},"events":[],"notes":["No events output"]}' > docs/data/events.json
          fi

      - name: Commit & push
        run: |
          git config user.name  "aom-harvester-bot"
          git config user.email "aom-bot@noreply.local"
          git add docs/data/events.json
          git commit -m "site: update events.json [skip ci]" || echo "No changes"
          git push
