name: AOM – Harvest & Publish

on:
  workflow_dispatch: {}
  schedule:
    # every day at 07:05 UTC
    - cron: "5 7 * * *"

permissions:
  contents: write   # needed to commit snapshots + site data

env:
  PYTHON_VERSION: "3.11"
  WINDOW_DAYS: "180"
  CITY: ""
  STATE: ""
  COUNTRY: ""
  KEYWORDS: ""      # e.g. "steampunk, victorian"
  ICS_FEEDS: ""     # comma-separated .ics URLs

concurrency:
  group: aom-harvest
  cancel-in-progress: false

jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install deps (if any)
        run: |
          python -m pip install --upgrade pip
          pip install -q requests beautifulsoup4 lxml ics || true

      - name: Run harvester
        env:
          WINDOW_DAYS: ${{ env.WINDOW_DAYS }}
          CITY: ${{ env.CITY }}
          STATE: ${{ env.STATE }}
          COUNTRY: ${{ env.COUNTRY }}
          KEYWORDS: ${{ env.KEYWORDS }}
          ICS_FEEDS: ${{ env.ICS_FEEDS }}
        run: |
          python harvest.py
          # Normalize output -> events.json
          if [ -f "aom-events.json" ]; then mv -f aom-events.json events.json; fi
          test -s events.json || (echo "events.json not found or empty" && exit 1)

      - name: Stage site data
        run: |
          mkdir -p docs/data
          cp -f events.json docs/data/events.json

      - name: Save raw snapshot (dated)
        run: |
          YEAR=$(date -u +%Y)
          MONTH=$(date -u +%m)
          TS=$(date -u +%Y%m%d-%H%M%S)
          mkdir -p docs/data/archive/${YEAR}/${MONTH}
          cp -f events.json docs/data/archive/${YEAR}/${MONTH}/raw-${TS}.json
          echo "Snapshot: docs/data/archive/${YEAR}/${MONTH}/raw-${TS}.json"

      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # auto-provided by Actions
        run: |
          git config user.name  "aom-bot"
          git config user.email "aom-bot@users.noreply.github.com"
          git add docs/data/events.json docs/data/archive
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "publish: events + snapshot ($(date -u +%Y-%m-%dT%H:%M:%SZ))"
            git push origin HEAD:main
          fi
