name: AOM Harvester (ICS-first)

on:
  workflow_dispatch:
    inputs:
      keywords:
        description: "Comma keywords (e.g., steampunk,victorian,renaissance,faire)"
        required: false
      window_days:
        description: "Days ahead to include (default 180)"
        required: false

  schedule:
    - cron: "7 9 * * *"   # daily at 09:07 UTC; change as you like

jobs:
  harvest:
    runs-on: ubuntu-latest
    env:
      KEYWORDS: ${{ github.event.inputs.keywords }}
      WINDOW_DAYS: ${{ github.event.inputs.window_days }}
      USE_DEMO_FEED: "1"             # set to "0" once you add your real feeds
      ICS_FEEDS: ""                  # optional: comma-separated ICS URLs (or use feeds.txt)
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests icalendar python-dateutil

      - name: Run harvester
        run: python harvest.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aom-events
          path: |
            events.json
            events.csv
            events.md
          if-no-files-found: warn
